<a href="https://colab.research.google.com/github/avinashnarra11/Tensor_flow/blob/main/Intro.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import tensorflow as tf

#Operations Class


In [2]:
print(tf.__version__)

1.3.0


In [3]:
hello = tf.constant("Hello")

In [7]:
world = tf.constant("World")

In [4]:
type(hello)

tensorflow.python.framework.ops.Tensor

In [5]:
print(hello)

Tensor("Const:0", shape=(), dtype=string)


In [9]:
with tf.Session() as sess:
    result = sess.run(hello+world)

In [11]:
print(result) 

b'HelloWorld'


In [12]:
print(tf.get_default_graph())

In [13]:
graph_one = tf.get_default_graph()

In [14]:
graph_two = tf.Graph()

In [16]:
print(graph_two)

In [17]:
sess = tf.InteractiveSession()

In [18]:
my_tensor = tf.random_uniform((4,4))

In [24]:
my_var = tf.Variable(initial_value= my_tensor)

In [28]:
#sess.run(my_var) doesnot work.
#We cannot run the uninitialized variable my_var

In [33]:
init = tf.global_variables_initializer()

In [34]:
sess.run(init)

In [35]:
sess.run(my_var)

array([[0.79149294, 0.9387727 , 0.26962566, 0.11714041],
       [0.37079966, 0.82634187, 0.05828655, 0.7437786 ],
       [0.02560842, 0.66544855, 0.8564489 , 0.7732128 ],
       [0.15760744, 0.8888345 , 0.25943398, 0.39038277]], dtype=float32)

In [36]:
ph = tf.placeholder(tf.float32, shape = (None,5))

TF Graphs

In [37]:
import numpy as np

In [41]:
np.random.seed(101)
tf.set_random_seed(101)

In [42]:
rand_a = np.random.uniform(0,100,(5,5))

In [43]:
rand_a

array([[51.63986277, 57.06675869,  2.84742265, 17.15216562, 68.52769817],
       [83.38968626, 30.69662197, 89.36130797, 72.15438618, 18.99389542],
       [55.42275911, 35.2131954 , 18.18924027, 78.56017619, 96.54832224],
       [23.23536618,  8.35614337, 60.35484223, 72.89927573, 27.62388285],
       [68.53063288, 51.78674742,  4.84845374, 13.78692376, 18.69674261]])

In [44]:
rand_b = np.random.uniform(0,100,(5,1))

In [46]:
rand_b

array([[99.43179012],
       [52.06653967],
       [57.87895355],
       [73.48190583],
       [54.19617722]])

In [47]:
a = tf.placeholder(tf.float32)

In [48]:
b= tf.placeholder(tf.float32)

In [53]:
add_op = a+b

In [54]:
mul_op = a*b

In [58]:
with tf.Session() as sess:
    add_result = sess.run(add_op, feed_dict = {a:rand_a,b:rand_b})
    print(add_result)
    mul_result = sess.run(mul_op, feed_dict = {a:rand_a,b:rand_b})
    print(mul_result)

[[151.07166  156.49855  102.27921  116.58396  167.95949 ]
 [135.45622   82.76316  141.42784  124.22093   71.06043 ]
 [113.30171   93.09215   76.06819  136.43912  154.42728 ]
 [ 96.71727   81.83804  133.83675  146.38118  101.10579 ]
 [122.72681  105.982925  59.044632  67.9831    72.89292 ]]
[[5134.644   5674.25     283.12433 1705.4707  6813.8315 ]
 [4341.8125  1598.267   4652.734   3756.8293   988.94635]
 [3207.8113  2038.1029  1052.7742  4546.9805  5588.1157 ]
 [1707.379    614.02527 4434.989   5356.7773  2029.8555 ]
 [3714.0984  2806.6438   262.76764  747.19855 1013.292  ]]


Example Neural Network

In [59]:
n_features = 10
n_dense_neurons = 3

In [60]:
x = tf.placeholder(tf.float32,(None,n_features))