<a href="https://colab.research.google.com/github/avinashnarra11/Tensor_flow/blob/main/Regression_Using_Tf.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [33]:
import tensorflow as tf
import pandas as pd

In [34]:
housing = pd.read_csv('/content/cal_housing_clean.csv')

In [35]:
housing.head()

housingMedianAge  totalRooms  ...  medianIncome  medianHouseValue
0              41.0       880.0  ...        8.3252          452600.0
1              21.0      7099.0  ...        8.3014          358500.0
2              52.0      1467.0  ...        7.2574          352100.0
3              52.0      1274.0  ...        5.6431          341300.0
4              52.0      1627.0  ...        3.8462          342200.0

[5 rows x 7 columns]

In [36]:
x_data = housing.drop('medianHouseValue',axis=1)

In [37]:
dep = housing['medianHouseValue']

In [38]:
from sklearn.model_selection import train_test_split

In [39]:
X_train, X_test, y_train, y_test = train_test_split( x_data, dep, test_size=0.3, random_state=101)

In [40]:
from sklearn.preprocessing import MinMaxScaler

In [41]:
scaler = MinMaxScaler()

In [42]:
scaler.fit(X_train)

MinMaxScaler(copy=True, feature_range=(0, 1))

In [43]:
X_train = pd.DataFrame(data= scaler.transform(X_train), columns= X_train.columns, index=X_train.index)

In [44]:
X_test = pd.DataFrame(data=scaler.transform(X_test), columns=X_test.columns, index=X_test.index)

In [45]:
housing.columns

Index(['housingMedianAge', 'totalRooms', 'totalBedrooms', 'population',
       'households', 'medianIncome', 'medianHouseValue'],
      dtype='object')

In [46]:
age = tf.feature_column.numeric_column('housingMedianAge')
rooms = tf.feature_column.numeric_column('totalRooms')
bedrooms = tf.feature_column.numeric_column('totalBedrooms')
pop = tf.feature_column.numeric_column('population')
households = tf.feature_column.numeric_column('households')
income = tf.feature_column.numeric_column('medianIncome')

In [47]:
feat_cols = [age,rooms,bedrooms,pop,households,income]

Modeling:

In [48]:
input_func = tf.estimator.inputs.pandas_input_fn(x= X_train, y=y_train, batch_size=10, num_epochs=1000, shuffle= True)

In [58]:
Model = tf.estimator.DNNRegressor(hidden_units=[10,10,10], feature_columns= feat_cols)

INFO:tensorflow:Using default config.
INFO:tensorflow:Using config: {'_model_dir': '/tmp/tmp7ln7aypv', '_tf_random_seed': 1, '_save_summary_steps': 100, '_save_checkpoints_secs': 600, '_save_checkpoints_steps': None, '_session_config': None, '_keep_checkpoint_max': 5, '_keep_checkpoint_every_n_hours': 10000, '_log_step_count_steps': 100}


In [59]:
Model.train(input_fn=input_func, steps=20000)

INFO:tensorflow:Create CheckpointSaverHook.
INFO:tensorflow:Saving checkpoints for 1 into /tmp/tmp7ln7aypv/model.ckpt.
INFO:tensorflow:loss = 823345400000.0, step = 1
INFO:tensorflow:global_step/sec: 484.699
INFO:tensorflow:loss = 604855530000.0, step = 101 (0.209 sec)
INFO:tensorflow:global_step/sec: 679.526
INFO:tensorflow:loss = 478255800000.0, step = 201 (0.147 sec)
INFO:tensorflow:global_step/sec: 526.419
INFO:tensorflow:loss = 143533330000.0, step = 301 (0.189 sec)
INFO:tensorflow:global_step/sec: 588.229
INFO:tensorflow:loss = 317499100000.0, step = 401 (0.171 sec)
INFO:tensorflow:global_step/sec: 543.651
INFO:tensorflow:loss = 142968080000.0, step = 501 (0.183 sec)
INFO:tensorflow:global_step/sec: 523.279
INFO:tensorflow:loss = 102338620000.0, step = 601 (0.193 sec)
INFO:tensorflow:global_step/sec: 528.282
INFO:tensorflow:loss = 116849570000.0, step = 701 (0.188 sec)
INFO:tensorflow:global_step/sec: 553.237
INFO:tensorflow:loss = 50791030000.0, step = 801 (0.190 sec)
INFO:tenso

In [60]:
pred_input_func = tf.estimator.inputs.pandas_input_fn(x=X_test,batch_size=10, num_epochs=1, shuffle=False)

In [61]:
predictions = Model.predict(input_fn= pred_input_func)
final_pred= list(predictions)

INFO:tensorflow:Restoring parameters from /tmp/tmp7ln7aypv/model.ckpt-20000


In [62]:
final_pred[:20]

[{'predictions': array([249782.9], dtype=float32)},
 {'predictions': array([360919.5], dtype=float32)},
 {'predictions': array([205252.64], dtype=float32)},
 {'predictions': array([194409.03], dtype=float32)},
 {'predictions': array([319113.5], dtype=float32)},
 {'predictions': array([194624.58], dtype=float32)},
 {'predictions': array([220099.6], dtype=float32)},
 {'predictions': array([205586.42], dtype=float32)},
 {'predictions': array([232670.38], dtype=float32)},
 {'predictions': array([227678.17], dtype=float32)},
 {'predictions': array([203209.69], dtype=float32)},
 {'predictions': array([216374.14], dtype=float32)},
 {'predictions': array([191740.47], dtype=float32)},
 {'predictions': array([180752.8], dtype=float32)},
 {'predictions': array([264956.56], dtype=float32)},
 {'predictions': array([187948.25], dtype=float32)},
 {'predictions': array([195484.44], dtype=float32)},
 {'predictions': array([195188.83], dtype=float32)},
 {'predictions': array([186366.7], dtype=float32)},

In [63]:
y_pred=[]
for i in final_pred:
  y_pred.append(i['predictions'])


In [64]:
y_pred

[array([249782.9], dtype=float32),
 array([360919.5], dtype=float32),
 array([205252.64], dtype=float32),
 array([194409.03], dtype=float32),
 array([319113.5], dtype=float32),
 array([194624.58], dtype=float32),
 array([220099.6], dtype=float32),
 array([205586.42], dtype=float32),
 array([232670.38], dtype=float32),
 array([227678.17], dtype=float32),
 array([203209.69], dtype=float32),
 array([216374.14], dtype=float32),
 array([191740.47], dtype=float32),
 array([180752.8], dtype=float32),
 array([264956.56], dtype=float32),
 array([187948.25], dtype=float32),
 array([195484.44], dtype=float32),
 array([195188.83], dtype=float32),
 array([186366.7], dtype=float32),
 array([264530.62], dtype=float32),
 array([175222.56], dtype=float32),
 array([240397.69], dtype=float32),
 array([216628.78], dtype=float32),
 array([172833.89], dtype=float32),
 array([180895.88], dtype=float32),
 array([299056.2], dtype=float32),
 array([177638.66], dtype=float32),
 array([136425.9], dtype=float32),


**Root Mean Square Error**

In [65]:
from sklearn.metrics import mean_squared_error

In [66]:
mean_squared_error(y_test,y_pred)**0.5

92949.01463164638